# Generated by Django 5.1.1 on 2024-10-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eiad', '0002_remove_blogpost_updated_at_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
